### ISSUE TITLE
User status display

### ISSUE THREAD

**Issue by miraten** [BookpalLab/meteor-shine#14]
User status display such as connected, login, logout etc.

**Comment by sangyoo91** [comment]
user-online branch created. This retrieves all online-users in a bootstrap modal.

**Comment by sangyoo91** [comment]
@miraten @DavidSunny Show followers/friends only? Show all users then display online/offline? Or show all online users.

**Comment by miraten** [comment]
leesangwon:connection 패키지를 통해서 구현하고 이 수준에서 일단 중지
