### ISSUE TITLE
User Profile implementation - Photo upload and crop

### ISSUE THREAD

**Issue by miraten** [BookpalLab/meteor-shine#21]

**Comment by DavidSunny** [comment]
라이브러리 추가 : http://fengyuanchen.github.io/cropper/
라이브러리 추가 예정 : http://camanjs.com/

**Comment by sangyoo91** [comment]
둘다 좋은 플러그인 같습니다.

**Comment by DavidSunny** [comment]
[cropperjs](http://fengyuanchen.github.io/cropper/)와 [cloudinary](www.cloudinary.com/)를

이용하여 프로필 이미지 업로드 기능 구현 완료

이미지 로테이션 부분에서 cropperjs의 bug가 있는 것 같아 추후 기능 추가를 할 예정임
