### ISSUE TITLE
Home UX

### ISSUE THREAD

**Issue by sangyoo91** [BookpalLab/meteor-shine#22]
현재 접속하면 `블로그 목록`이 `home`에서 뜹니다.

현재로써는 이 부분이 `tree-menu`에서 `Blog > 블로그 목록`과 겹치는데, 

Home을 좀 더 Home 답고 이에 맞는 기능/UX를 생각해보면 좋을 것 같습니다.

반대로 Home을 목록으로 두고, Blog를 부분적으로 나누는건 어떨까 싶습니다.

e.g.,

1. Home = Blog List
 --> Sort : Newest, Popular, Most Visited, Followers/Friends?, Favorites
2. New Blog Post
3. User Profile --> My Blogs/ Favorites

**Comment by DavidSunny** [comment]
우선순위에 따른 이슈 해결을 위해 임시적으로 closed
