### ISSUE TITLE
Saving the draft when editing a post

### ISSUE THREAD

**Issue by miraten** [BookpalLab/meteor-shine#37]
Post를 작성할 때, draft를 저장하는 기능을 구현한다.
Draft는 저자가 일정한 시간(3~5초) 동안 입력이 없는 경우, 자동으로 현재까지의 작업된 부분을 저장해두는 기능을 의미한다.
Draft는 저자가 저장(또는 발행) 버튼을 누르면 정상적인 blog 글로 변경된다.
한 저자에 대하여 복수의 draft 글이 저장될 수 있다.

**Comment by sangyoo91** [comment]
Autosave - HTML5 Local Storage
User Save - Server DB 

유저가 포스트시 draft 지워짐

**Comment by DavidSunny** [comment]
issue closed.
