### ISSUE TITLE
Favorite: 좋아하는글 담아서 저장하는 기능 

### ISSUE THREAD

**Issue by splex7** [BookpalLab/meteor-shine#57]
- 다른 사람들의 포스트를 읽다가 좋아하는 글을 발견하면 저장할 수 있다.
- 저장된 포스트를 Favorite 메뉴에서 다시 볼 수 있다. 
- 저장된 포스트를 삭제할 수 있다.

**Comment by DavidSunny** [comment]
우선순위에 따른 이슈 해결을 위해 임시적으로 closed
