### ISSUE TITLE
profile image 변경시 로딩시간

### ISSUE THREAD

**Issue by splex7** [BookpalLab/meteor-shine#59]
사진을 변경하고 난뒤 저장을 누른후 창이 바로 닫히는데 약 2초정도 사진이 변경되지 않으므로
방금 처리한 내용이 제대로 작동한다는 느낌이 들지 않으므로, 
창을 천천히 닫거나 로딩 이미지나 메시지가 있으면 더 좋을거 같습니다.

**Comment by DavidSunny** [comment]
현재 클라우디네리 업로드 방식 옵션을 최적화하며 이미지 로딩시간을 줄임

현재 progress-bar를 통해 작동중인 상태를 보여줌으로 로딩이미지를 넣지 않기로함
