### ISSUE TITLE
permission control for post authors

### ISSUE THREAD

**Issue by miraten** [BookpalLab/meteor-shine#86]
actions on the post : read, edit, publish, and remove

permissions
- read : read
- write : edit only
- admin: all the action. (author has the 'admin' permission of his/her post)

actions on the category: read, write, admin
- read : can read all the posts in the category
- write : can register a new post in the category
- admin : can admin all the posts in the category

**Comment by DavidSunny** [comment]
제목정보 | 제목2정보 |
------------ | -----------
[다음](www.daum.net) | www.naver.com |

**Comment by miraten** [comment]
구현 완료
